name: home_widget_example
description: Demonstrates how to use the home_widget plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  workmanager:
    git:
      url: https://github.com/sunalwaysknows/flutter_workmanager
      ref: f37742bcf612c51e9571d623138a21a90a5992ea

  home_widget:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

