name: home_widget
description: A plugin to provide a common interface for creating HomeScreen Widgets for Android and iOS.
version: 0.7.1
repository: https://github.com/ABausG/home_widget
funding:
  - https://github.com/sponsors/ABausG/
topics:
  - home-screen-widget
  - native
  - android
  - ios
screenshots:
  - description: 'iOS Counter HomeScreen Widget'
    path: pub/screenshots/ios-counter.gif
  - description: 'Android HomeScreen Widget'
    path: pub/screenshots/android.png
documentation: https://docs.page/ABausG/home_widget

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.20.0-1.2.pre'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  path_provider_foundation: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: es.antonborri.home_widget
        pluginClass: HomeWidgetPlugin
      ios:
        pluginClass: HomeWidgetPlugin
