name: home_widget_example
description: Demonstrates how to use the home_widget plugin.

publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependency_overrides:
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager
      path: workmanager
      ref: d94eb34

dependencies:
  flutter:
    sdk: flutter
  workmanager: ^0.5.2
  home_widget:
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  device_info_plus: ^9.0.3
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

